# Generated by Django 2.1.5 on 2020-07-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='msg',
        ),
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'sent'), (2, 'wait')], default=2),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
